### ISSUE TITLE
Question: Nuxt

### ISSUE THREAD

**Issue by mcombalicer** [creativetimofficial/vue-now-ui-dashboard-pro#2]
Hi,

I'm currently trying to plug this theme into nuxt. I've copied the components, layouts, etc... into the nuxt designated folders and have only changed the directory to make sure that the components are referenced correctly.

However, it is giving me a "Cannot read property 'showSidebar' of undefined" error. Any idea?

Thanks!

**Comment by cristijora** [comment]
Hi @mcombalicer Thanks for using the product and for the question.
For the sidebar you can try this piece of code.
```js
let app = new Vue({
      data: {
        sidebarStore: SidebarStore
      }
    })
Vue.prototype.$sidebar = app.sidebarStore
```
Instead of lines 33-45 in `SidebarPlugin/index.js` and see if this works. The problem is around having a reactive store for the sidebar. Let me know if this approach works and I will change it in the next update because this approach should work both with or without nuxt.

**Comment by mcombalicer** [comment]
Hi @cristijora Thank you but it is still throwing the same error.
I found a workaround though. In my ``` dashboard-plugins.js ``` instead of using 

```
export default {
  install(Vue) {
    Vue.use(GlobalComponents);
    Vue.use(GlobalDirectives);
    Vue.use(SideBar);
    Vue.use(Notifications);
    Vue.use(VeeValidate, { fieldsBagName: 'veeFields' });
  }
}
```
I used and the code you gave for Notifications and it worked. 
```
Vue.use(GlobalComponents);
Vue.use(GlobalDirectives);
Vue.use(SideBar);
Vue.use(Notifications);
Vue.use(VeeValidate, { fieldsBagName: 'veeFields' });
```
The only difference I noticed is that the sidebar is expanded on load rather than minimised but that is not a big deal. ;)

Thank you for your help
